@ENDPOINT=https://nivjnanmbtnz5rtcqu7hi3rfcq0ugeon.lambda-url.ap-southeast-1.on.aws/

POST {{ENDPOINT}}
Content-Type: application/json

{"stripeChargeObject":{"name":"ABC Company","description":"ABC Company Invoice 112","currency":"HKD","amount":11760},"stripeToken":{"id":"tok_1MjpCdKTVzBhQcQi5gPib6y5","object":"token","card":{"id":"card_1MjpCcKTVzBhQcQiBMOBqVt0","object":"card","address_city":null,"address_country":null,"address_line1":null,"address_line1_check":null,"address_line2":null,"address_state":null,"address_zip":null,"address_zip_check":null,"brand":"Visa","country":"US","cvc_check":"unchecked","dynamic_last4":null,"exp_month":12,"exp_year":2034,"funding":"credit","last4":"4242","name":"hello@calvin-c.com","tokenization_method":null},"client_ip":"192.47.255.14","created":1678390359,"email":"hello@calvin-c.com","livemode":false,"type":"card","used":false}}

###

OPTIONS {{ENDPOINT}}
Content-Type: application/json

{
  "abc": 123
}